### ISSUE TITLE
MG: Review 4.1.0

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_python#134]
Hi Matt,

We are about to release `gslab_python` and template v4.1.0. Release notes are [here for template](https://github.com/gslab-econ/template/pull/85#issuecomment-327258103) and [here for `gslab_python`](https://github.com/gslab-econ/gslab_python/pull/125#issuecomment-328713637). Please install `gslab_python` and clone template, each from the branch `4.1.0`. 

The task list was [here](https://github.com/gslab-econ/gslab_python/issues/101#issue-249128581). The original meeting notes are [here](https://github.com/gslab-econ/admin/issues/115#issue-247201402).

Please let me know if you have any questions. Thanks!

**Comment by stanfordquan** [comment]
@gentzkow Please be reminded of this review task. Thanks!

**Comment by gentzkow** [comment]
Thanks. Not forgotten! Just pushed behind some other things in the queue.

**Comment by gentzkow** [comment]
Hi @stanfordquan,

Finally getting a chance to work on this.

I'm getting a bit stuck on an elementary step I'd appreciate your advice on: Right now I have Python 2.7.14 installed via Homebrew at /usr/local/bin/python2 plus the Python 2.7.10 installed as part of Mac OS at /usr/bin/python. By default, the executable for the former is 'python2' and the executable for the latter is 'python'. Naturally when I run the template scripts they install gslab tools etc. as part of the latter, but the former is what I want to be using.

I'm not committed to using the Homebrew version -- I just want to know what best practice is. Do you guys just use the system python on your macs directly? Or have you installed the updated version of Python separately without Homebrew?

**Comment by arosenbe** [comment]
Hi @gentzkow. I also brewed my installation of Python 2.7.14, but I don't use the default python2 executable. Instead, I set my PYTHONPATH environment variable (in my bash profile) to the path of my brewed installation. This way `python` executes my brewed installation. 

Our template recognizes this setup. The config script for the SConstruct loads the PYTHONPATH into the SCons environment, and Python figures out the paths in this setting. You can read more at gslab-econ/template#90.

This doesn't mesh with your current setup, but it should be enough to get the template running. If you do like your current environment (e.g., if you're often calling the default Mac python installation) or don't like this solution, we can definitely figure something else out.

**Comment by gentzkow** [comment]
(As an alternative, I installed 2.7.14 directly from the Python website [here](https://www.python.org/downloads/mac-osx/). This overrides the system's python executable so seems to work fine. So the only question is whether there's a way to make sure scons plays nice with homebrew-installed python.)

**Comment by gentzkow** [comment]
Thanks @arosenbe.

Just to clarify:
1. How do you point 'python' in the terminal to the brewed version? (The current Homebrew installs to 'python2' by default.) Did you use an alias in .bash_profile?
2. If you're calling that binary, why do you need to use PYTHONPATH explicitly? 

Other questions:
1. Where do I find documentation for the valid options in config_user and config_global?
2. I am trying to run the Stata script in the template. I uncommented the relevant lines in analysis/source/prepare_data/Sconsript and the builder line in analysis/Sconstruct. I also added 'prereq_Stata = Yes' to config_global. But then when I run 'run.py' or 'scons' the system hangs on "scons: Reading SConscript files ...". If I interrupt and try running scons again I get this error:

> scons: Reading SConscript files ...
AttributeError: 'NoneType' object has no attribute 'keys':
  File "/Users/gentzkow/Git/template/analysis/SConstruct", line 11:
    [mode, vers, cache_dir, PATHS, pythonpath] = configuration(ARGUMENTS)
  File "../config/configuration.py", line 66:
    if input_assets_key not in val.keys():

This seems to be related to the fact that it has created an empty config_user.yaml. If I delete that and try again, it hangs (without the error) like the first time.

**Comment by arosenbe** [comment]
@gentzkow, the executable for my brewed installation is python (in usr/local/bin). I don't remember switching the defaults, but it's possible that I did. I get the "pointing" right by prepending usr/local/bin to my PATH in my bash_profile. This way 'python' references my brewed installation and not the default Mac installation. I've seen this path editing as best practice when using homebrew.

As for why I need PYTHONPATH, brewing python correctly redirects the path for pip installations into usr/local. The brewed Python binary wasn't searching these locations by default, so I used PYTHONPATH to make sure it would. I don't have a more technical explanation than that at the moment. This seems above board, since I'm not messing with any objects that Python wouldn't use by default.

### Other Questions 

1. This should be in the first and second question of the FAQ. 
2. Did you comment out the Python build command in the same SConscript? Only one can be active at a time. See "What software can I use" in the FAQ. 

Maybe @Shun-Yang can help more with debugging. I'm far from a computer waiting for a ~sea~train.

**Comment by gentzkow** [comment]
Thanks @arosenbe. Sorry to interrupt your vacation! None of this is urgent, and we can defer until you're back. @Shun-Yang: feel free to jump in as well but also feel free to wait until you're back at work.

When you come back you can tell me what a seatrain is.

To my earlier questions:
1. I saw the FAQ. But it isn't clear (i) whether the 3 options shown for config_user.yaml are all the valid options in the default template or if there are others; (ii) what are the valid options for config_global.yaml. On the latter, for example, I couldn't see where to look for the right field to use to say Stata, R, etc. are required.

2. I see the same behavior even if only the Stata lines are uncommented. As far as the FAQ, I don't see "what software can I use." There is a short section on "can I use other software for data analysis?" but it does not say anything about uncommenting only one at a time.

**Comment by stanfordquan** [comment]
Thanks @arosenbe for stepping in and answer these questions. My followups: 

> I saw the FAQ. But it isn't clear (i) whether the 3 options shown for config_user.yaml are all the valid options in the default template or if there are others; (ii) what are the valid options for config_global.yaml. On the latter, for example, I couldn't see where to look for the right field to use to say Stata, R, etc. are required.

I'm not sure I understand your question correctly but this is my attempt at an answer. Re: (i), the available options for `config_user.yaml` are repo-dependent, and the ones shown in the FAQ are the ones needed to run the default template (with Stata). Since we haven't needed to use any user-specified option for, e.g., R, we don't have those listed.

> I see the same behavior even if only the Stata lines are uncommented. As far as the FAQ, I don't see "what software can I use." There is a short section on "can I use other software for data analysis?" but it does not say anything about uncommenting only one at a time.

I was able to reproduce this bug: it occurs if `config_user.yaml` exists but is blank. It seems that a failed build (which seems to be what happened when you had to exit) produce a blank `config_user.yaml` file. I will fix so that this does not happen _and_ we're more forgiving/informative when it does.

**Comment by arosenbe** [comment]
Thanks @stanfordquan, you just beat me to the punch. I'm filling in on @gentzkow's question 1 (ii) about default options in `config_global`. 

The default options are just those appearing in the versioned file and [`external`](https://github.com/gslab-econ/template/blob/43b9f14e1028c0dde6e48ba1ea283dc85e70c9d6/README.md#what-is-config_globalyaml). We don't do software checks in config_global because it's redundant with the builders loaded in the SConstruct. Commenting and uncommenting those lines should be sufficient (decided [here](https://github.com/gslab-econ/template/issues/63#issuecomment-325456488)). 

---

The "what software can I use" section is [here](https://github.com/gslab-econ/template/blob/43b9f14e1028c0dde6e48ba1ea283dc85e70c9d6/README.md#what-software-can-i-use-for-data-analysis).

**Comment by arosenbe** [comment]
@stanfordquan, I was thinking about @gentzkow issue with the homebrewed python executable named python2, not python. This seems like something that's likely to happen again, and we don't want a dependency to be 

> Python 2.7 not installed by homebrew.

One thought is to apply the same behavior of the stata builder—try a default but allow a user override—to our other builders. I don't think this should be too tough since the machinery's already in place. A bigger question is just whether we would like this behavior. (If we make this change, we need to also update run.py.)

**Comment by gentzkow** [comment]
Thanks guys! I understand now about config_global.yaml. I had been thinking the prereq_git-lfs switch indicated that this was a place to list all software prerequisites.

**Comment by gentzkow** [comment]
Small bug: In config/config_python.py line 8:

> pip.main(['install', '--upgrade', 'git+http://git@github.com/gslab-econ/gslab_python.git@v4.1.0'])

@v4.1.0 should be replaced by @4.1.0.

**Comment by gentzkow** [comment]
Numbering notes from here on...

1. In order to run config/config_python.py user needs pip installed. Should be added to dependencies.

2. In order to run analysis scripts user needs numpy and matplotlib. Should be added to dependencies.

**Comment by gentzkow** [comment]
3. I can now run the baseline template successfully, but when I first run the /analysis/ directory it takes a very long time -- it spends ~2min on "scons: Reading SConscript files ..." Should fix.

**Comment by gentzkow** [comment]
4. I would think the debrief_args section of SConstruct should be part of config_global.yaml

**Comment by gentzkow** [comment]
3. (revised) It's clearer now what's going on. For some reason on line 24 of SConstruct

>                               'BuildStata' : Builder(action = gs.build_stata),

the process stalls because it is waiting for some input from the user, though there is no prompt indicating that. It hangs on "scons: Reading SConscript files ..." indefinitely; if I press return it continues and finishes normally.

**Comment by gentzkow** [comment]
5. I think it would be a good idea to revise the config_global and config_user scripts in the template so that each directory has both; each script has all valid options included, commented out if they are not needed; and each script include commented instructions explaining what each option means, what the default is if it's not specified, etc. This way these scripts are fully self-documenting.

**Comment by gentzkow** [comment]
@arosenbe, @stanfordquan: Can you remind me the protocol we settled on for logging the state of external inputs / data assets? (Suppose I'd like to add an external data file to be used in the template and be sure that it's state will be logged.)

**Comment by arosenbe** [comment]
@gentzkow, You add an `input` key to either/both `config_*.yaml` file. All the values under this key will be recorded in  `release/state_of_input.log`. We walk nested dictionaries but also accept single strings. 

The name of the `input` key can be changed within template, and the log's name will automatically update to reflect the change. 

Example [specification](https://github.com/gslab-econ/template/blob/43b9f14e1028c0dde6e48ba1ea283dc85e70c9d6/paper_slides/config_global.yaml#L15) and [log](https://github.com/gslab-econ/template/blob/43b9f14e1028c0dde6e48ba1ea283dc85e70c9d6/paper_slides/release/state_of_input.log).

**Comment by gentzkow** [comment]
@arosenbe: I've now completed my review. Sorry it took so long! I have not had a chance to test all the different functionalities (e.g., I haven't experimented with the cache tools yet) but I was able to run everything and use the key pieces.

Overall it looks great. While I can see some areas for further improvement, I don't think it makes sense to delay any further.

I would vote that you open a task to address the small points in my numbers 1-5 above and then we can merge to master and make the current versions live for gslab_python and template.

Once that's done, I'd like you guys to give us an assessment of how much effort it would be to convert each of our currently active repositories to the new format. Based on that we can prioritize for which it is worth paying that fixed cost.
