### ISSUE TITLE
Fix windows bug in stata

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/gslab_python#57]
See https://github.com/gslab-econ/template/pull/35#issuecomment-277465418. Fix both the gslab_python and template side of things.

**Comment by stanfordquan** [comment]
I'll look at this and pull the change into `dev_four` as part of the 4.0 release

**Comment by stanfordquan** [comment]
I found the bug. It's indeed interesting, so I document it here for GSLab posterity (especially for those working on Windows).

In Python 2.7 and subsequent, both of the following code snippets return `True`:

```
velvet  = "the world's behind you"
command = "%% Watch out %s"
command % velvet == "% Watch out the world's behind you"
```

```
command = "%% Watch out the world's behind you"
command == "%% Watch out the world's behind you"
```

Basically you need to escape the percent sign with another one _only_ when you're doing a substitution, but not otherwise. This behaviour can make things very confusing when we need to call `%STATAEXE%` from `cmd`.

**Comment by stanfordquan** [comment]
@lboxell please find only relevant pull request [here](https://github.com/gslab-econ/template/pull/37). This bug is not related to gslab_python stata builder --- it rests entirely in the template's setup.py. Everything should work as intended now.

**Comment by stanfordquan** [comment]
Pulled [template branch](https://github.com/gslab-econ/template/pull/37). Issue closed!
