### ISSUE TITLE
Test 4.0 on Linux

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/gslab_python#63]
See https://github.com/gslab-econ/gslab_python/issues/58#issuecomment-295779749

**Comment by lboxell** [comment]
The metropolis-beamer template is going to be an issue for linux... I think we should not have it as a requirement and just use a native beamer template for the slides. For our projects, we can then switch which beamer template we use.

**Comment by gentzkow** [comment]
Yes. I agree with making the default a build-in theme.

I think we should apply this principle more generally: Make as many
requirements as possible optional rather than mandatory. E.g., can we allow
the template to work for someone who doesn't want to use R and/or Stata? Or
who wants to use latex rather than Lyx?
-- 

Matthew Gentzkow
Professor of Economics
Stanford University

**Comment by lboxell** [comment]
Closing task.

Summary:
- Tested template on linux. See https://github.com/gslab-econ/gslab_python/issues/63#issuecomment-295870864
