### ISSUE TITLE
Test 4.0 on Windows

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/gslab_python#64]
See https://github.com/gslab-econ/gslab_python/issues/58#issuecomment-295779749

**Comment by stanfordquan** [comment]
Resetting windows VM now.

**Comment by stanfordquan** [comment]
How to add environment variables [Mac](https://apple.stackexchange.com/questions/106778/how-do-i-set-environment-variables-on-os-x) [Windows](https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them)

`gslab_python` doesn't actually require Stata MP, just a Stata. 
We should specify `%STATAEXE%` vs `StataMP-64.exe` paths for Windows?

Be more specific and concise about `stata yaml`. Maybe we should fork it?
 
 ```
 net from https://raw.githubusercontent.com/sergiocorreia/stata-misc/master/
 cap ado uninstall yaml
 net install yaml
 ```

We should have an `install git` step

Example `PATH` for Windows

Be more specific about SCons version.

The yaml modules should probably be under their respective programs. Also need a lot more obvious installation instructions. `install.packages("yaml")`

Windows scons install require adding python to registry.

Need setuptools, i.e. need pip, i.e. need [get-pip.py install](https://github.com/BurntSushi/nfldb/wiki/Python-&-pip-Windows-installation). `pip` automatically installs `setuptools`, and you should probably install `pip` anyway.

It's not clear to me why we force the user to have a cache. We should at least discuss that if we make them write it into their user config.

We also don't explain what `user-config.yaml` does, what are the options for statamp, so forth.

The user warning for mtheme is clunky (also wrong)

The logging function seems to not be adding newlines correctly

The R builder is failing. Command line argument issue (QL fixed in gslab_python)
