### ISSUE TITLE
Add cache reconfiguration code

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_python#99]
Can switch between one and two numeral naming.

#### Add our own instructions on configuring the SCons cache to the readme and add code to gslab_scons. See [here](https://github.com/gslab-econ/gslab_python/issues/71)

**Comment by arosenbe** [comment]
I've done a bit of searching, and it seems that the discrepancy in single vs. double indexing of the cache is related to the SCons version. Versions before 2.5.0 use single indexing and no `config` file in the cache, while versions after use double indexing and a `config` file to store that indexing information. [source](https://bitbucket.org/scons/scons/src/rel_2.5.1/src/CHANGES.txt?at=2.5.1&fileviewer=file-view-default#CHANGES.txt-60)

When a version of SCons >= 2.5.0 encounters a cache created by an older version, it recognizes the discrepancy and yells at you. 

When the opposite happens, and an old SCons encounters a cache created by the newer version, it ignores the cached, double-indexed files and populates the cache with freshly built, single-indexed files. Running SCons >= 2.5.0 on this mixed up cache will simply ignore the single-indexed files, and it won't yell at you. 

I think the issue wasn't that SCons switched between single and double indexing. Rather some users had a version of SCons before 2.5.0 and others had version 2.5.0 or later. New users shouldn't encounter this problem because SCons >= 2.5.0 is currently the default for pip, homebrew, anaconda, and [SCons's download page](http://scons.org/pages/download.html).

---

I suggest that we do not package `scons-configure-cache.py`. Rather we do one of the following:
* Package scons-local 2.5.1
* Mention the issue with older versions of SCons (true dependency is SCons >= 2.4.0) and point to SCons's own solution in our FAQ.

**Comment by arosenbe** [comment]
@yuchuan2016, can you look over my suggestion at https://github.com/gslab-econ/gslab_python/issues/99#issuecomment-326145577? I'd lean toward packaging scons-local (which I think you have experience with) but am open to suggestions.

**Comment by arosenbe** [comment]
@lboxell, thought you might be interested in https://github.com/gslab-econ/gslab_python/issues/99#issuecomment-326145577.

**Comment by lboxell** [comment]
@arosenbe,

That seems consistent with what I'd seen before. For some reason, it was happening every so often in the lab still. I guess there could have been an old version of scons floating around on someones desktop/sherlock/etc.

**Comment by arosenbe** [comment]
@lboxell I checked the current lab computers, and we're all now running SCons >= 2.5.0. Though I definitely could have been using an older version at the time.

**Comment by yuchuan2016** [comment]
@arosenbe , great. I have nothing to add. Do we want to implement `scons-local` now?

**Comment by arosenbe** [comment]
That'd be my vote. Are you cool with that?

**Comment by arosenbe** [comment]
Under PR by @yuchuan2016 at gslab-econ/template#83.

**Comment by arosenbe** [comment]
PR passed at gslab-econ/template#83.  Merge commit: https://github.com/gslab-econ/template/commit/8c91db5a464f69c4a5b0c34bb8d306f65428730b

Include zipped scons local distribution and SConstruct-level wrappers to execute the local scons. Updates README with 
* appropriate instructions for getting started
* how to use system-wide scons installation
* pointer to problems with the cache
